version: "3"

services:

  controller:
    build:
      context: ..
      dockerfile: ./docker/controller/Dockerfile
    image: 172.26.174.105:5001/fire/controller
    container_name: fire-controller
    ports:
      - 5000:5000
    command: --db_uri=mysql://root:HON123well@172.26.174.105:3306/fire --kafka=172.26.174.105:9092
    restart: always
#    depends_on:
#      - db
#      - kafka

  analyst:
    build:
      context: ..
      dockerfile: ./docker/analyst/Dockerfile
    image: 172.26.174.105:5001/fire/analyst
    container_name: fire-analyst
    command: http://172.26.174.105:5000 172.26.174.105:9092 amqp://rqadmin:rqadmin@wxweb1.chinacloudapp.cn:5672
    depends_on:
      - controller
    restart: always
    deploy:
      replicas: 10
