version "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=HON123well
    volumes:
      - /etc/mysql/conf.d:/etc/mysql/conf.d
      - /var/lib/mysql:/var/lib/mysql
    container_name: mysql
    ports:
      - 3306:3306
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --max_allowed_packet=128M

  kafka:
    image: spotify/kafka
    restart: always
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOST=172.26.174.105
      - ADVERTISED_PORT=9092

  controller:
    build:
      context: ..
      dockerfile: ./controller/Dockerfile
    image: fire/controller
    container_name: fire-controller
    ports:
      - 5000:5000
    command: --db_uri=mysql://root:HON123well@172.26.174.105:3306/fire --kafka=172.26.174.105:9092
    restart: always

  analyst:
    build:
      context: ..
      dockerfile: ./analyst/Dockerfile
    image: fire/analyst
    container_name: fire-analyst
    command: http://172.26.174.105:5000 172.26.174.105:9092

